apiVersion: example.org/v1alpha1
kind: WebAppClaim
metadata:
  name: my-webapp
  namespace: default
spec:
  compositionRef:
    name: webapps.example.org 
  parameters:
    image: nginx:latest
    replicas: 3
