---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.my.domain
  resources:
  - demos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.my.domain
  resources:
  - demos/finalizers
  verbs:
  - update
- apiGroups:
  - apps.my.domain
  resources:
  - demos/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.oleh.v
  resources:
  - demoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.oleh.v
  resources:
  - demoes/finalizers
  verbs:
  - update
- apiGroups:
  - apps.oleh.v
  resources:
  - demoes/status
  verbs:
  - get
  - patch
  - update
